# Generated by Django 3.0.4 on 2020-03-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='discount_price',
            field=models.FloatField(default=False),
        ),
    ]
