# Generated by Django 3.0.4 on 2020-03-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200319_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
